version: '3'

services:
  app:
    build:
      context: .
      entrypoint: .docker/entrypoint.sh
      container_name: prismaapi-app
      ports:
        - "3000:3000"
      dockerfile: Dockerfile

